version: '3'

networks:
    laravel:

services:

    nginx:
        networks: 
            - laravel
        image: nginx:stable-alpine
        ports:
            - "7777:80"
        volumes:
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php

    mysql:
        image: mysql:5.7.22
        restart: unless-stopped
        networks: 
            - laravel
        tty: true
        ports:
            - "7778:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment: 
            MYSQL_DATABASE: 
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql

    php:
        build: 
            context: ./
            dockerfile: Dockerfile
        networks:
            - laravel
        volumes:
            - ./src:/var/www/html
        ports:
            - "7779:9000"
        depends_on: 
            - mysql